name: Sinister
version: '${project.version}'
main: com.AgarthaMC.Sinister.Main
api-version: 1.17
authors: [ QulexTheBuilder ]
description: So spooky so sinister

commands:
  Sinister:
    usage: /Sinister
    description: Test
  PotionEvent:
    usage: /Potionevent
    description: Test

permissions:
  spawnMob:
    default: op
  changeSpawner:
    default: op
  spawnItem:
    default: op
  reload:
    default: op
  killTasks:
    default: op
  doPotionRain:
    default: op