name: SinisterMobs
version: '${project.version}'
main: com.QulexTheBuilder.sinistermobs.Main
api-version: 1.17
authors: [ QulexTheBuilder ]
description: Make Custom Mobs

commands:
  sinisterMobs:
    usage: /sinistermobs
    description: Test
  PotionEvent:
    usage: /potionevent
    description: Test

permissions:
  spawnMob:
    default: op
  changeSpawner:
    default: op
  spawnItem:
    default: op
  reload:
    default: op
  killTasks:
    default: op
  doPotionRain:
    default: op